# Generated by Django 3.2.8 on 2021-10-23 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
