# Generated by Django 3.2.8 on 2021-10-23 11:11

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg'])], verbose_name='image'),
        ),
    ]
